### ISSUE TITLE
Import dashboard not working

### ISSUE THREAD

**Issue by himulawang** [Ingensi/dockbeat#127]
I try to 

``` bash
curl -XPUT 'http://elastic:9200/_template/dockbeat' -d@etc/dockbeat.template.json

{"acknowledged":true}
```

Then refresh kibana. Can't find dockbeat dashboard in dashboard panel.

Any idea?

**Comment by himulawang** [comment]
Sorry, I misunderstand the template meaning. It's not a dashboard template.

**Comment by marminthibaut** [comment]
No problem ;)
