### ISSUE TITLE
metricbeat docker plugin

### ISSUE THREAD

**Issue by strarsis** [Ingensi/dockbeat#140]
Could development of dockbeat and metricbeat docker plugin be merged?: 
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-docker.html

Dockbeat in contrast to the metricbeat docker plugin seems to be stable and production-ready.

**Comment by erwanncloarec** [comment]
Well for me the code is already merged.
I would recommend to use the metricbeat plugin since it's Elastic that maintain it now.

What kind of problems do you encounter with the metricbeat plugin that you don't have in dockbeat ?

**Comment by strarsis** [comment]
Then dockbeat has been merged with/is a metricbeat plugin now?

**Comment by erwanncloarec** [comment]
Yes! It's mainly the same code except for the plugin part

**Comment by strarsis** [comment]
Thanks! It may be nice to add a notice about this to the README of this project.
Will changes to this repository be merged to the ES plugin and the other way around on a regular basis?

**Comment by erwanncloarec** [comment]
I think we will deprecate this repo and redirect to metricbeat
We will update the README soon :)

**Comment by strarsis** [comment]
OK, thanks for your answers.
