### ISSUE TITLE
Plans to update for ES6?

### ISSUE THREAD

**Issue by robertjustjones** [Ingensi/dockbeat#148]
After updating to Elasticsearch 6.x, I'm getting this error.
```
ERR Failed to perform any bulk index operations: 406 Not Acceptable
```

I know es6 deprecates mapping types, which dockbeat relies on, in favor of separate indices for each type. There's also a new stricter requirement to specify Content-Type.

Is there any plan or work underway to make that change?  Or are there alternative approaches?

**Comment by ruflin** [comment]
@robertjustjones The docker module in Metricbeat was contributed to dockbeat team. Best start using metricbeat with the docker module which is updated.

**Comment by robertjustjones** [comment]
Thanks!!
